#!/usr/bin/env bash
export ENVIRONMENT=prod
export DB_HOST=127.0.0.1
export DB_PORT=5432
export DB_USER=postgres
export DB_PASS=postgres
export DB_NAME=acmhr
export MAX_CONNECTION=50
export MY_PORT=2401
